name: Check syntax of changed files in a pull request

on:
  # Triggers the workflow when a new commit is pushed to the HEAD ref of a pull request
  pull_request:
    types: [opened, reopened, synchronize]
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:
env:
  TOKEN: ${{ secrets.WCMS_ENT_GITHUB_TOKEN }}
jobs:
  checksyntax:
    runs-on: [ wcs-gh-p02-group ]
    steps:
      - uses: actions/checkout@v3
      - name: CHECK SYNTAX
        run: |
          sh .github/workflows/scripts/check_syntax.sh

